Ot146 35 endpoint para listar usuarios
alkemyTech/OT146-SERVER pull request #27
Opened 2022-02-25 05:07 UTC by felapton89

### SUMMARY

1. GET all users.
2. GET actives users.
3. GET deleted users.
4. PreAuthorize waiting
5. Create Users and Roles in data.sql

![Captura de pantalla de 2022-02-25 01-58-28](https://user-images.githubusercontent.com/68129105/155657135-7d711c2a-4e94-44d9-9617-7f720a9765fc.png)
![Captura de pantalla de 2022-02-25 01-59-00](https://user-images.githubusercontent.com/68129105/155657141-78a6102d-c27a-4771-be7f-514f4475eb9e.png)
![Captura de pantalla de 2022-02-25 01-59-16](https://user-images.githubusercontent.com/68129105/155657150-cd7ceaf9-241e-4292-ba6b-808b48938cc2.png)

2022-02-25 13:35 UTC, paoliellolucas requested changes

2022-02-25 13:35 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +                .collect(Collectors.toList());
static import para poder leer .collect(toList());

2022-02-25 13:35 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/repository/UserRepository.java
> +    @Query(nativeQuery = true,
nada de native queries estimado 😜
Usemos lo q nos brinda spring-data. 
Proba algo como esto:
List<UserEntity> findByDeleted(boolean isDeleted);

Y en el defaultGateway llamas a este metodo con la banderita correspondiente

2022-02-25 13:35 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controller/UserController.java
> +                .collect(Collectors.toList());
recordemos usar static imports para poder leer:
.collect(toList()) en lugar de .collect(Collectors.toList()).
Como estamos dentro del metodo collect.. es redundante leer otra vez Collectors.toList

2022-02-25 13:35 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controller/UserController.java
> +    @GetMapping("/actives")
podemos simplificar estos 2 endpoints (actives y deleted) en uno solo y jugar con el parámetro q nos llega.
Ej:
/users?deleted=true(para los borrados)
/users?deleted=false(para los activos)

Aprovechemos para jugar con la anotación @RequestParam 😃.
Con este cambio podemos simplificar todos los métodos que siguen (en el servicio y gateway). En lugar d tener 2, vas a tener 1 y jugas con el booleano al momento de llamar al repository.findByDeleted(true/false)

2022-02-25 21:26 UTC, felapton89 commented
![Captura de pantalla de 2022-02-25 18-18-36](https://user-images.githubusercontent.com/68129105/155805098-b605f9fc-c379-4560-a2e7-6688a06a612c.png)
![Captura de pantalla de 2022-02-25 18-18-51](https://user-images.githubusercontent.com/68129105/155805124-fef364b6-0007-4181-ad9d-e4d4f34df62e.png)
![Captura de pantalla de 2022-02-25 18-19-06](https://user-images.githubusercontent.com/68129105/155805143-1c42ad0b-4f9e-4f37-8c22-ad0357474fe0.png)
![Captura de pantalla de 2022-02-25 18-19-15](https://user-images.githubusercontent.com/68129105/155805157-aa4449e5-9250-433a-982f-8e29aa011fe7.png)

2022-02-26 14:05 UTC, paoliellolucas requested changes

2022-02-27 22:06 UTC, paoliellolucas approved these changes

2022-02-27 22:06 UTC, merged