Ot146 56/57 creacion y detalles
alkemyTech/OT146-SERVER pull request #39
Opened 2022-02-28 19:26 UTC by dantemogni

Corresponde a los tickets:
- OT146-56 Detalle slides
- OT146-57 Creacion slides

2022-03-01 00:33 UTC, paoliellolucas requested changes

2022-03-01 00:33 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultSlidesGateway.java
> +        slideEntity.setDeleted(false);
esto x default ya esta en false asi q no seria necesario

2022-03-01 00:33 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultSlidesGateway.java
> +        SlidesEntity slideToFind = slidesRepository
slide es un mejor nombre para la variable. Muy techie slideToFind..

2022-03-01 00:33 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/slides/Slides.java
> +    private Long organizationId;
tendría que ser el objeto Organization q esta en domain

2022-03-02 15:49 UTC, dantemogni commented on src/main/java/com/alkemy/ong/data/gateways/DefaultSlidesGateway.java
> +        slideEntity.setDeleted(false);
Si le saco esa línea, me tira error diciendo que la columna deleted no puede ser nula, es decir, no me la está completando con el valor por defecto. 
![imagen](https://user-images.githubusercontent.com/52411075/156396463-3c1c266f-1970-4ba4-aeff-a0aa4d6d4670.png)

2022-03-03 21:45 UTC, paoliellolucas approved these changes

2022-03-03 21:45 UTC, merged