Ot146 84 agregar documentación con swagger
alkemyTech/OT146-SERVER pull request #43
Opened 2022-03-03 02:24 UTC by Noblega-Diego

Create Swagger Document
and added easy url access for document ui

2022-03-03 12:58 UTC, paoliellolucas requested changes

2022-03-03 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controller/SwaggerController.java
> +public class SwaggerController {
En lugar de agregar uno propio, podemos usar lo default q viene con swagger? Tratemos d usar el comportamiento standard
De esta forma.. este controller tmb aparece en la doc y no es necesario.

2022-03-03 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controller/TestimonialController.java
> +    @ApiOperation(value = "Save Testimonial")
si me fijo el modelo (TestimonialDTO), no me figura requerido (con asterisco rojo), el name q es notNull.
Por ultimo, no olvidar subir la evidencia!

2022-03-04 02:10 UTC, Noblega-Diego commented
new Evidence 
![image](https://user-images.githubusercontent.com/53923511/156685703-676d3686-9bb7-470b-ba0a-5ec11dee7d22.png)

2022-03-04 19:57 UTC, merged