Ot146 57 endpoint creacion slides
alkemyTech/OT146-SERVER pull request #61
Opened 2022-03-08 21:37 UTC by dantemogni

En el Jira dejé algunas screens!

2022-03-11 12:52 UTC, paoliellolucas requested changes

2022-03-11 12:52 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultSlidesGateway.java
> +        byte[] decodedBytes = Base64.decode(trimmedEncodedImage);
no creo q sea responsabilidad de la capa de base de datos todo esto, ya que esta ligado al feature de amazon.
Redefiniria la estructura de esta forma:
El defaultStorageGateway no debería estar en el paquete data. Podríamos crear un nuevo paquete cloud (x ej) a la misma altura q data y ahi poner lo relacionado a aws. Por que cloud en lugar de aws? Porque queremos dar la libertad q en otro momento se cambie a otro cloud.

Con esto ordenado, no estaría bien que el paquete data este acoplado al paquete cloud. Quien es el que tiene que unir todo? El dominio 😃. El dominio debería subir la imagen (usando el storageGateway en cloud) y cuando obtiene la url, dsp pasársela a la base y seguir el flujo.

Con estos cambios, vemos un mejor manejo de responsabilidades, vemos la fuerza del dominio como coordinador (siempre trabajando con temas del dominio) y dejamos las implementaciones de base de datos y cloud q hagan su aporte!

2022-03-11 14:14 UTC, dantemogni commented on src/main/java/com/alkemy/ong/data/gateways/DefaultSlidesGateway.java
> +        byte[] decodedBytes = Base64.decode(trimmedEncodedImage);
> El dominio debería subir la imagen (usando el storageGateway en cloud) y cuando obtiene la url, dsp pasársela a la base y seguir el flujo.

No sé si te sigo bien con eso. Lo que hice con lo que me decís fue refactorizar el código que era para decodificar la base64 y crear el CustomMultipartFile, en el DefaultStorageGateway que a su vez lo moví a el package 'cloud'. Hasta ahi todo bien?

Después, el dominio en sí, por lo que tenia entendido no tiene implementaciones de nada, verdad? Es decir, tiene la interfaz del gateway, el service y el POJO representando la entidad (o la imagen en este caso). Pero todo el comportamiento va a parar en el DeaultStorageGateway.. es así?

2022-03-11 19:48 UTC, paoliellolucas requested changes

2022-03-11 19:48 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/cloud/DefaultCloudGateway.java
> +public class DefaultCloudGateway implements CloudGateway {
aca podemos ser mas pro.. y nombrar a la clase DefaultAwsGateway! Asi no quedan dudas de que tecnología estamos usando!

2022-03-11 19:48 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/cloud/CustomMultipartFile.java
> +package com.alkemy.ong.domain.cloud;
esta es una conversion entre tipos de datos.. q no tiene q ver con lo cloud.. ponelo dentro de domain-utils

2022-03-13 17:20 UTC, paoliellolucas approved these changes

2022-03-13 17:20 UTC, merged