OT146-28 | Crear modelo y repositorio de Slides
alkemyTech/OT146-SERVER pull request #7
Opened 2022-02-18 15:36 UTC by dantemogni

2022-02-20 15:40 UTC, dantemogni commented on src/main/java/com/alkemy/ong/data/entity/SlidesEntity.java
> +    private Long organizationId;
El campo "auditoria" que seria?

2022-02-21 14:17 UTC, paoliellolucas requested changes

2022-02-21 14:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/SlidesEntity.java
> +    private Long organizationId;
updatedAt y createdAt

2022-02-21 20:56 UTC, paoliellolucas approved these changes

2022-02-21 20:56 UTC, merged