Ot146 74 crear modelo repositorio y servicio de comentarios
alkemyTech/OT146-SERVER pull request #8
Opened 2022-02-18 16:31 UTC by felapton89

### **SUMMARY**

1.  _- Commentary:_ 
    - Body
    - User_Id
    - News_id (waiting for the entity)
2.  Commentary Service interface in **domain** (waiting for DTO parammeter)
3.  Implementation interface in **data** with the logic for _**DTO --> Entity**_.
4. Add Commentary sql in schema.sql

2022-02-18 19:00 UTC, paoliellolucas requested changes

2022-02-19 14:43 UTC, paoliellolucas requested changes

2022-02-19 14:43 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateway/DefaultCommentaryGateway.java
> +        Optional<UserEntity> user = userRepository.findById(commentary.getUserId().getId());
aca vas a tener q considerar las excepciones.. por ejemplo que cuando hagas el findById no lo encuentre. 
Como spring data trabaja con optionals podrías hacer un findById().orElseThrow(exception).
Esta excepción puede extender de Runtime asi no tenes que manejarla con try-catch.
Y si tenemos un global exception handler (ControllerAdvice) en la capa web.. golazo! Ya que podríamos manejar de forma centralizada las excepciones!

2022-02-21 15:24 UTC, felapton89 commented on src/main/java/com/alkemy/ong/data/entity/CommentaryEntity.java
> +    @ManyToOne(fetch = FetchType.LAZY, optional = false)
@OneToOne y @ManyToOne: default ---> Eager
@OneToMany y @ManyToMany: default ---> Lazy

2022-02-21 17:49 UTC, felapton89 commented
![Captura de pantalla de 2022-02-21 14-30-18](https://user-images.githubusercontent.com/68129105/155005241-ca808fbd-ba57-40d7-922e-9607b684d29d.png)
![Captura de pantalla de 2022-02-21 14-31-10](https://user-images.githubusercontent.com/68129105/155005250-9fec7a76-af83-4a9e-bc30-5dcfd26a1946.png)
![Captura de pantalla de 2022-02-21 14-31-32](https://user-images.githubusercontent.com/68129105/155005262-d61ff3cb-2782-4cef-a86b-2f0510b3d4a4.png)
![Captura de pantalla de 2022-02-21 14-36-50](https://user-images.githubusercontent.com/68129105/155005283-056550f4-607f-4b6f-a4d7-b81686301607.png)

2022-02-21 21:25 UTC, paoliellolucas requested changes

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateway/DefaultCommentaryGateway.java
> +                .collect(Collectors.toList());
podemos usar static import para leer:
.collect(toList)

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateway/DefaultCommentaryGateway.java
> +                .map(entity -> new Commentary(entity.getUserId().getId(), entity.getBody(), entity.getNewsId().getId()))
dentro del map, podes extraer esa lógica a un método que se llame toDto(), entonces podes decir:
map(this::toDto()) para que quede mas legible.

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateway/DefaultCommentaryGateway.java
> +                        () -> new EntityNotFoundException("User with id: " + commentary.getUserId() + " not found.")
podes extraer como una constante el mensaje ya que se repite para users y news

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateway/DefaultCommentaryGateway.java
> +        UserEntity user = userRepository.findById(commentary.getUserId())
podes extraer esta logica a un private getUser() y lo mismo para getNews().. asi no leemos tanto de ese código en este método de creación

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateway/DefaultCommentaryGateway.java
> +        CommentaryEntity entity = new CommentaryEntity();
hay una buena anotación de Lombok que es builder. Implementa el patron con el mismo nombre e instancia el objeto entity de una con todo completo. Pégale una mirada!

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/repository/CommentaryRepository.java
> +    @Query(nativeQuery = true,
no usemos native query ya que spring-data lo implementa por nosotros automáticamente.
Borrando esa anotación todo funciona automáticamente :p

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/comments/CommentaryGateway.java
> +    void create(Commentary commentary);
en realidad no retorna void, debería retornar el comentario que se creo con su id generado.

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/CommentaryController.java
> +        List<Commentary> models = commentaryService.findAll();
en lugar de models, a esta variable la podes llamar commentaries

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/CommentaryController.java
> +                .collect(Collectors.toList());
podes usar el static reference para poder leer collect(toList());

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/CommentaryController.java
> +                .map(model -> (new CommentaryDtoResponse(model.getBody())))
ademas del body tmb podemos retornar datos del news y user. algunos para juegues..

2022-02-21 21:25 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/CommentaryController.java
> +class CommentaryDTO {
esta clase puede ser privada.. ya q solo la usamos en este controlador

2022-02-23 01:44 UTC, paoliellolucas approved these changes

2022-02-23 01:44 UTC, merged