Ot146 15 crear modelo y repositorio base organization
alkemyTech/OT146-SERVER pull request #9
Opened 2022-02-18 18:39 UTC by SolPiqueras

2022-02-18 19:26 UTC, paoliellolucas requested changes

2022-02-18 19:26 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/OrganizationEntity.java
> +    private LocalDateTime deletedAt;
updatedAt should be this name

2022-02-18 19:26 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/OrganizationEntity.java
> +    private Boolean isDelete;
deleted should be this name

2022-02-18 19:26 UTC, paoliellolucas commented on src/main/resources/application.yml
> +    password: root
no es buena practica subir las passwords. Dejemos vacío este campo

2022-02-18 19:26 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +    age int
age era de mi vieja tabla. Te recomiendo copiar lo ultimo de main ( a mano si queres para simplificar) y debajo tu script. En esta sección lo único q tengo q ver es en verde tu script. Ningún otro cambio como este rojo!

2022-02-19 13:17 UTC, paoliellolucas approved these changes

2022-02-19 13:20 UTC, paoliellolucas requested changes

2022-02-19 13:20 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +   PRIMARY KEY (id)}
quedo una llave q no tiene q ir acá

2022-02-19 13:20 UTC, paoliellolucas commented on pom.xml
> +        <dependency>
mejor usemos la dependencia de spring-validation
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>

2022-02-21 20:02 UTC, paoliellolucas requested changes

2022-02-22 12:51 UTC, paoliellolucas requested changes

2022-02-22 12:51 UTC, paoliellolucas commented on pom.xml
> +        <dependency>
En main ahora esta esta dependencia. Esta duplicada ahora. Deja la q ya esta!

2022-02-22 12:51 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +    @Autowired
al usarlo por constructor, esta anotación ya no es necesaria :)

2022-02-22 12:51 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +    private OrganizationRepository organizationRepository;
es buena practica trabajar con private final para las dependencias de los beans!

2022-02-22 12:51 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +    public Organization toModel(OrganizationEntity organizationEntity){
este metodo puede ser public ya que solo se usa en esta clase. Lo mismo para el toEntity

2022-02-22 12:51 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/organization/OrganizationGateway.java
> +  List<OrganizationEntity> findAll();
Recordemos que como estamos en el domain, no conocemos de entities. Acá todos los métodos deben recibir o retornar objetos del dominio (organization). Nada de organizationEntity.

2022-02-22 12:51 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/organization/OrganizationService.java
> +    private OrganizationGateway organizationGateway;
private final

2022-02-22 19:18 UTC, SolPiqueras commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +    public Organization toModel(OrganizationEntity organizationEntity){
private en vez de public, no?

2022-02-23 21:33 UTC, merged